functionsDirectory = "/Users/jasonstacks/novapa/novapawebsite/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/jasonstacks/novapa/novapawebsite"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run check"
functions = "/Users/jasonstacks/novapa/novapawebsite/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "https://www.northernvirginiaperformingarts.org/*"
to = "https://novapa.org/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://northernvirginiaperformingarts.org/*"
to = "https://novapa.org/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://www.novapa.org/*"
to = "https://novapa.org/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/summer"
to = "/summer-2027"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/be-in-frozen"
to = "/be-in-frozen.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/frozen"
to = "/register/?season=fall&utm_source=playbill&utm_medium=print&utm_campaign=frozen-playbill"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/summer.html"
to = "/summer-2027.html"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/camp-info"
to = "/summer-2027.html"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/camp-info.html"
to = "/summer-2027.html"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/shrek"
to = "/index.html#shows"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/shrek.html"
to = "/index.html#shows"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/coaching-registration"
to = "/register/?coaching"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/coaching-registration.html"
to = "/register/?coaching"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/novapa_registration"
to = "/register/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/novapa_registration.html"
to = "/register/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/teen_conservatory_auditions"
to = "/teen-conservatory.html"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/teen_conservatory_auditions.html"
to = "/teen-conservatory.html"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]